---
- name: Create n8n directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  loop:
    - /home/{{ ansible_user }}/n8n-docker
    - /home/{{ ansible_user }}/n8n-data
    - /home/{{ ansible_user }}/n8n-data/videos

- name: Set permissions for n8n-data directory
  file:
    path: "{{ item }}"
    owner: 1000
    group: 1000
    mode: '0755'
  become: yes
  loop:
    - /home/{{ ansible_user }}/n8n-data
    - /home/{{ ansible_user }}/n8n-data/videos

- name: Copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /home/{{ ansible_user }}/n8n-docker/docker-compose.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Copy Dockerfile
  template:
    src: Dockerfile.j2
    dest: /home/{{ ansible_user }}/n8n-docker/Dockerfile
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0644'

- name: Start n8n container
  shell: docker-compose up -d --build
  args:
    chdir: /home/{{ ansible_user }}/n8n-docker
  become: yes
  # Using shell module for docker-compose up is simpler when using the standalone binary
  # Alternatively, 'community.docker.docker_compose' could be used but requires python dependencies.
